
-------------------------------------------------------------------------------------------
-- Brisanje tabela
DROP TABLE UREDJUJE CASCADE CONSTRAINTS;
DROP TABLE OCENA_RECENZENTA CASCADE CONSTRAINTS;
DROP TABLE ANGAZOVANJE_RECENZENT CASCADE CONSTRAINTS;
DROP TABLE RUNDA_RECENZIJE CASCADE CONSTRAINTS;
DROP TABLE AUTORSTVO CASCADE CONSTRAINTS;
DROP TABLE CITAT CASCADE CONSTRAINTS;
DROP TABLE PUBLIKACIJA CASCADE CONSTRAINTS;
DROP TABLE ANGAZOVANJE CASCADE CONSTRAINTS;
DROP TABLE TELEFON_INSTITUCIJA CASCADE CONSTRAINTS;
DROP TABLE MAIL_INSTITUCIJA CASCADE CONSTRAINTS;
DROP TABLE NAUCNA_OBLAST CASCADE CONSTRAINTS;
DROP TABLE NI_INSTITUCIJA CASCADE CONSTRAINTS;
DROP TABLE TELEFON CASCADE CONSTRAINTS;
DROP TABLE MAIL CASCADE CONSTRAINTS;
DROP TABLE ISTRAZIVAC CASCADE CONSTRAINTS;
DROP TABLE AUTOR CASCADE CONSTRAINTS;
DROP TABLE OBLASTI_EKSPERTIZE CASCADE CONSTRAINTS;
DROP TABLE RECENZENT CASCADE CONSTRAINTS;
DROP TABLE UREDNIK CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRATOR_OVLASCENJA CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRATOR_REPOZITORIJUMA CASCADE CONSTRAINTS;
DROP TABLE RUKOVODILAC_PROJEKTA CASCADE CONSTRAINTS;
DROP TABLE ULOGA CASCADE CONSTRAINTS;
DROP TABLE DATASET CASCADE CONSTRAINTS;
DROP TABLE PODRZANE_PLATFORME CASCADE CONSTRAINTS;
DROP TABLE SOFTVERSKI_ARTIFAKT CASCADE CONSTRAINTS;
DROP TABLE TEHNICKI_IZVESTAJ CASCADE CONSTRAINTS;
DROP TABLE KNJIGA_ILI_POGLAVLJA CASCADE CONSTRAINTS;
DROP TABLE NAUCNI_RAD CASCADE CONSTRAINTS;
DROP TABLE OSTALI_DOKUMENTI CASCADE CONSTRAINTS;
DROP TABLE PRIPADAJUCI_FAJLOVI CASCADE CONSTRAINTS;
DROP TABLE VERZIJA CASCADE CONSTRAINTS;
DROP TABLE KLJUCNE_RECI CASCADE CONSTRAINTS;
DROP TABLE ISTRAZIVACKI_REZULTAT CASCADE CONSTRAINTS;

-------------------------------------------------------------------------------------------
-- Brisanje sekvenci
DROP SEQUENCE SEQ_ISTRAZIVACKI_REZULTAT; 
DROP SEQUENCE SEQ_ISTRAZIVAC;
DROP SEQUENCE SEQ_ULOGA; 
DROP SEQUENCE SEQ_NI_INSTITUCIJA; 
DROP SEQUENCE SEQ_PUBLIKACIJA; 
DROP SEQUENCE SEQ_OCENA_RECENZENTA;

-------------------------------------------------------------------------------------------
-- Kreiranje sekvenci
CREATE SEQUENCE SEQ_ISTRAZIVACKI_REZULTAT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ISTRAZIVAC          START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_ULOGA               START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_NI_INSTITUCIJA      START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_PUBLIKACIJA         START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_OCENA_RECENZENTA    START WITH 1 INCREMENT BY 1 ;

-------------------------------------------------------------------------------------------
-- Kreiranje baze podataka za upravljanje istraživačkim rezultatima
CREATE TABLE istrazivacki_rezultat(
    ID_IR NUMBER(10) PRIMARY KEY,
    NASLOV VARCHAR2(100) NOT NULL,
    APSTRAKT VARCHAR2(500) NOT NULL,
    DATUM_KREIRANJA DATE NOT NULL,
    DATUM_OBJAVLJIVANJA DATE NOT NULL,
    STATUS_IR VARCHAR2(20) DEFAULT 'U_PRIPREMI' NOT NULL,
    VIDLJIVOST NUMBER(1) DEFAULT 1 NOT NULL,

    CONSTRAINT CHK_STATUS CHECK (STATUS_IR IN ('U_PRIPREMI','POSLAT_NA_RECENZIJU','U_REVIZIJI','PRIHVACEN','ODBIJEN','OBJAVLJEN','ARHIVIRAN')),

    CONSTRAINT CHK_VIDLJIVOST CHECK (VIDLJIVOST IN (0,1))

);

    --Kjucne reci atributi
    CREATE TABLE kljucne_reci(
        ID_IR NUMBER(10) NOT NULL,
        KLJUCNA_REC VARCHAR2(50) NOT NULL,
        CONSTRAINT PK_KLJUCNE_RECI PRIMARY KEY (ID_IR, KLJUCNA_REC),
        CONSTRAINT FK_KLJUCNE_RECI_ID_IR FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE
    );
    -- Vezrije rezultata
    CREATE TABLE verzija
    (
        ID_IR NUMBER(10) NOT NULL,
        BROJ_VERZIJE NUMBER(10) NOT NULL,
        DATUM_POSTAVLJANJA DATE NOT NULL,
        OPIS_IZMENA VARCHAR2(500) NOT NULL,
        ODGOVORNA_OSOBA VARCHAR2(100) NOT NULL,

        CONSTRAINT PK_VERZIJA PRIMARY KEY (ID_IR, BROJ_VERZIJE),
        --Ima--
        CONSTRAINT FK_ID_IR_FAJL FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE
    );

        --Pripadajuci fajlovi atributi
        CREATE TABLE pripadajuci_fajlovi(

            ID_IR NUMBER(10) NOT NULL,
            BROJ_VERZIJE NUMBER(10) NOT NULL,
            NAZIV_FAJLA VARCHAR2(100) NOT NULL,

            CONSTRAINT PK_PRIPADAJUCI_FAJLOVI PRIMARY KEY (ID_IR, BROJ_VERZIJE, NAZIV_FAJLA),
            CONSTRAINT FK_ID_IR FOREIGN KEY (ID_IR, BROJ_VERZIJE) REFERENCES verzija(ID_IR, BROJ_VERZIJE) ON DELETE CASCADE
        );

--podklase istrazivackih rezultata
CREATE TABLE ostali_dokumenti(
    ID_IR NUMBER(10) PRIMARY KEY,
    OPCIJE VARCHAR2(100) NOT NULL,

    CONSTRAINT FK_OSTALI_DOKUMENTI_ID_IR FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE,
    CONSTRAINT CHK_OPCIJE CHECK (OPCIJE IN ('OBRAZOVNI_MATERIJAL','PREZENTACIJA','DOKTORSKA_DISERTACIJA'))
);

CREATE TABLE naucni_rad(
    ID_IR NUMBER(10) PRIMARY KEY,
    TIP_RADA VARCHAR2(100) DEFAULT 'CASOPIS' NOT NULL,
    NAZIV_CAS_KON VARCHAR2(100) NOT NULL,
    DOI VARCHAR2(100),
    ISSN_ILI_ISBN VARCHAR2(20),
    BROJ_SVESKE NUMBER(10) NOT NULL,
    BROJ_IZDANJA NUMBER(10) NOT NULL,
    BROJ_STRANICE NUMBER(10) NOT NULL,

    CONSTRAINT FK_NR_ID_IR FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE,
    CONSTRAINT CHK_TIP_RADA CHECK (TIP_RADA IN ('CASOPIS','KONFERENCIJA'))
);

CREATE TABLE knjiga_ili_poglavlja(
    ID_IR NUMBER(10) PRIMARY KEY,
    IZDAVAC VARCHAR2(100) NOT NULL,
    MESTO_IZDAVANJA VARCHAR2(100) NOT NULL,

    CONSTRAINT FK_KP_ID_IR FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE
);

CREATE TABLE softverski_artifakt(
    ID_IR NUMBER(10) PRIMARY KEY,
    PROGRAMSKI_JEZIK VARCHAR2(50) NOT NULL,
    REPO_LINK VARCHAR2(200) NOT NULL,
    NACIN_LICENCIRANJA VARCHAR2(100) NOT NULL,
    DOKUMENTACIJA VARCHAR2(200) NOT NULL,

    CONSTRAINT FK_SA_ID_IR FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE
);
    --podrzane platforme
    CREATE TABLE podrzane_platforme(
        ID_IR NUMBER(10) NOT NULL,
        PLATFORMA VARCHAR2(50) NOT NULL,

        CONSTRAINT CHK_PLATFORMA CHECK (PLATFORMA IN ('WINDOWS','LINUX','MACOS','WEB','ANDROID','IOS')),
        CONSTRAINT PK_PODRZANE_PLATFORME PRIMARY KEY (ID_IR, PLATFORMA),
        CONSTRAINT FK_PODRZANE_PLATFORME_ID_IR FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE
    );

CREATE TABLE tehnicki_izvestaj(
    ID_IR NUMBER(10) PRIMARY KEY,

    CONSTRAINT FK_TI_ID_IR FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE
);

CREATE TABLE dataset(
    ID_IR NUMBER(10) PRIMARY KEY,
    FORMAT VARCHAR2(50) NOT NULL,
    VELICINA NUMBER(10) NOT NULL,
    BROJ_ZAPISA NUMBER(10) NOT NULL,
    OPIS_STRUKTURE VARCHAR2(500) NOT NULL,
    PERIOD_OBUHVATA_PODATAKA VARCHAR2(100) NOT NULL,
    LICENCA_KORISCENJA VARCHAR2(100) NOT NULL,
    OGRANICENJA_PRISTUPA VARCHAR2(200) NOT NULL,

    CONSTRAINT FK_DS_ID_IR FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE
);

 ------------------------------------------------------------------------------------------------------------
-- Kreiranje tabele za Istraživače

CREATE TABLE istrazivac(
    ID_I NUMBER(10) PRIMARY KEY,
    IME VARCHAR2(50) NOT NULL,
    DATUM_RODJENJA DATE NOT NULL,
    DRZAVA VARCHAR2(50) NOT NULL,
    PREZIME VARCHAR2(50) NOT NULL,
    NAUCNA_OBLAST VARCHAR2(100) NOT NULL,
    NAUCNO_ZVANJE VARCHAR2(100) NOT NULL,
    STATUS_NAUCNIKA VARCHAR2(20) DEFAULT 'AKTIVAN' NOT NULL,

    CONSTRAINT CHK_STATUS_NAUCNIKA CHECK (STATUS_NAUCNIKA IN ('AKTIVAN','NEAKTIVAN'))
);

    -- Mail I Telefoni atributi
    CREATE TABLE mail(
        ID_I NUMBER(10) NOT NULL,
        MAIL VARCHAR2(100) NOT NULL,

        CONSTRAINT CHK_MAIL CHECK (REGEXP_LIKE(MAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
        CONSTRAINT PK_MAIL PRIMARY KEY (ID_I, MAIL),
        CONSTRAINT FK_MAIL_ID_I FOREIGN KEY (ID_I) REFERENCES istrazivac(ID_I) ON DELETE CASCADE
    );

    CREATE TABLE telefon(
        ID_I NUMBER(10) NOT NULL,
        TELEFON VARCHAR2(20) NOT NULL,

        CONSTRAINT CHK_TELEFON CHECK (REGEXP_LIKE(TELEFON, '^\+?[0-9]{9,15}$')),
        CONSTRAINT PK_TELEFON PRIMARY KEY (ID_I, TELEFON),
        CONSTRAINT FK_TELEFON_ID_I FOREIGN KEY (ID_I) REFERENCES istrazivac(ID_I) ON DELETE CASCADE
    );
-----------------------------------------------------------------------------------------------------------
-- Kreiranje tabele za Uloge

CREATE TABLE uloga(
    ID_U NUMBER(10) PRIMARY KEY,
    ID_I NUMBER(10),

    CONSTRAINT FK_ID_I FOREIGN KEY (ID_I) REFERENCES istrazivac(ID_I) ON DELETE CASCADE
);

CREATE TABLE rukovodilac_projekta(
    ID_U NUMBER(10) PRIMARY KEY,

    CONSTRAINT FK_RUKOVODILAC_ID_U FOREIGN KEY (ID_U) REFERENCES uloga(ID_U) ON DELETE CASCADE
);
--Administator repozitorijuma i njegova ovlašćenja
CREATE TABLE administrator_repozitorijuma(
    ID_U NUMBER(10) PRIMARY KEY,

    CONSTRAINT FK_ADMINISTRATOR_ID_U FOREIGN KEY (ID_U) REFERENCES uloga(ID_U) ON DELETE CASCADE
);
    --Administratorova ovlašćenja atributi
    CREATE TABLE Administrator_ovlascenja(
        ID_U NUMBER(10) NOT NULL,
        OVLASCENJE VARCHAR2(100) NOT NULL,
        CONSTRAINT FK_AO_ID_U FOREIGN KEY (ID_U) REFERENCES uloga(ID_U) ON DELETE CASCADE
    );

--Urednik
CREATE TABLE urednik(
    ID_U NUMBER(10) PRIMARY KEY,
    UREDJIVACKA_SEKCIJA VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_UREDNIK_ID_U FOREIGN KEY (ID_U) REFERENCES uloga(ID_U) ON DELETE CASCADE
);

--Recenzent i oblasti recenziranja
CREATE TABLE recenzent(
    ID_U NUMBER(10) PRIMARY KEY,
    CONSTRAINT FK_RECENZENT_ID_U FOREIGN KEY (ID_U) REFERENCES uloga(ID_U) ON DELETE CASCADE
);
    --Oblasti ekspertize atributi
    CREATE TABLE oblasti_ekspertize(
        ID_U NUMBER(10) NOT NULL,
        OBLAST_EKSPERTIZE VARCHAR2(100) NOT NULL,

        CONSTRAINT FK_RECENZENT_OBLASTI_ID_U FOREIGN KEY (ID_U) REFERENCES uloga(ID_U) ON DELETE CASCADE
    );

--Autor
CREATE TABLE autor(
    ID_U NUMBER(10) PRIMARY KEY,
    ORCID VARCHAR2(30) NOT NULL,

    CONSTRAINT CHK_ORCID CHECK (REGEXP_LIKE(ORCID, '^\d{4}-\d{4}-\d{4}-\d{3}[X\d]$')), ---prihvata samo sa X na kraju sa cifrom zeza
    CONSTRAINT FK_AUTOR_ID_U FOREIGN KEY (ID_U) REFERENCES uloga(ID_U) ON DELETE CASCADE
);
--------------------------------------------------------------------------------------------------------------
-- Kreiranje tabele za Naucnoistraživačke Institucije

CREATE TABLE ni_institucija(
    ID_NII NUMBER(10) PRIMARY KEY,
    NAZIV VARCHAR2(100) UNIQUE NOT NULL,
    ADRESA VARCHAR2(200) NOT NULL
);

    --Naucne Oblasti I Kontakti atributi

    CREATE TABLE naucna_oblast(
        ID_NII NUMBER(10) NOT NULL,
        NAUCNA_OBLAST VARCHAR2(100) NOT NULL,

        CONSTRAINT PK_NAUCNA_OBLAST_INSTITUCIJA PRIMARY KEY (ID_NII, NAUCNA_OBLAST),
        CONSTRAINT FK_NAUCNA_OBLAST_ID_NII FOREIGN KEY (ID_NII) REFERENCES ni_institucija(ID_NII) ON DELETE CASCADE
    );

    CREATE TABLE mail_institucija(
        ID_NII NUMBER(10) NOT NULL,
        MAIL VARCHAR2(100) NOT NULL,

        CONSTRAINT CHK_MAIL_INSTITUCIJA CHECK (REGEXP_LIKE(MAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
        CONSTRAINT PK_MAIL_INSTITUCIJA PRIMARY KEY (ID_NII, MAIL),
        CONSTRAINT FK_MAIL_ID_NII FOREIGN KEY (ID_NII) REFERENCES ni_institucija(ID_NII) ON DELETE CASCADE
    );

    CREATE TABLE telefon_institucija(
        ID_NII NUMBER(10) NOT NULL,
        TELEFON VARCHAR2(20) NOT NULL,

        CONSTRAINT CHK_TELEFON_INSTITUCIJA CHECK (REGEXP_LIKE(TELEFON, '^\+?[0-9]{9,15}$')),
        CONSTRAINT PK_TELEFON_INSTITUCIJA PRIMARY KEY (ID_NII, TELEFON),
        CONSTRAINT FK_TELEFON_ID_NII FOREIGN KEY (ID_NII) REFERENCES ni_institucija(ID_NII) ON DELETE CASCADE
    );

---------------------------------------------------------------------------------------------------------------
-- Kreiranje tabele za vezu Angazovanje Istraživača u Institucijama

CREATE TABLE angazovanje(
    ID_I NUMBER(10) NOT NULL,
    ID_NII NUMBER(10) NOT NULL,
    DATUM_ANGAZOVANJA DATE NOT NULL,
    DATUM_ZAVRSETKA DATE,
    ORGANIZACIONA_JEDINICA VARCHAR2(100) NOT NULL,
    NAZIV_POZICIJE VARCHAR2(100) NOT NULL,
    TIP_ANGAZOVANJA VARCHAR2(20) DEFAULT 'STALNI' NOT NULL,

    CONSTRAINT VREME_ANGAZOVANJA CHECK (DATUM_ZAVRSETKA IS NULL OR DATUM_ZAVRSETKA >= DATUM_ANGAZOVANJA),
    CONSTRAINT PK_ANGAZOVANJE PRIMARY KEY (ID_I, ID_NII),
    CONSTRAINT FK_ANGAZOVANJE_ID_I FOREIGN KEY (ID_I) REFERENCES istrazivac(ID_I) ON DELETE CASCADE,
    CONSTRAINT FK_ANGAZOVANJE_ID_NII FOREIGN KEY (ID_NII) REFERENCES ni_institucija(ID_NII) ON DELETE CASCADE,
    CONSTRAINT CHK_TIP_ANGAZOVANJA CHECK (TIP_ANGAZOVANJA IN ('STALNI','PRIVREMEN'))
);

-----------------------------------------------------------------------------------------------------------------
-- Publikacija

CREATE TABLE publikacija(
    ID_P NUMBER(10) PRIMARY KEY,
    ID_D NUMBER(10) UNIQUE,
    ID_TI NUMBER(10) UNIQUE,
    ID_SA NUMBER(10) UNIQUE,

    CONSTRAINT FK_PUBLIKACIJA_ID_D FOREIGN KEY (ID_D) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE,
    CONSTRAINT FK_PUBLIKACIJA_ID_TI FOREIGN KEY (ID_TI) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE,
    CONSTRAINT FK_PUBLIKACIJA_ID_SA FOREIGN KEY (ID_SA) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE
);

    -- Citat atributi
    CREATE TABLE citat(
        ID_P1 NUMBER(10) NOT NULL,
        ID_P2 NUMBER(10) NOT NULL,
        CITIRAJUCA_PUBLIKACIJA VARCHAR2(100) NOT NULL,
        CITIRANA_PUBLIKACIJA VARCHAR2(100) NOT NULL,
        TIP_CITATA VARCHAR2(20) DEFAULT 'INDIREKTAN' NOT NULL,
        MESTO_CITIRANJA VARCHAR2(100) NOT NULL,
        KONTEKST_CITIRANJA VARCHAR2(500) NOT NULL,

        CONSTRAINT PK_CITAT PRIMARY KEY (ID_P1, ID_P2),
        CONSTRAINT FK_CITAT_ID_P1 FOREIGN KEY (ID_P1) REFERENCES publikacija(ID_P) ON DELETE CASCADE,
        CONSTRAINT FK_CITAT_ID_P2 FOREIGN KEY (ID_P2) REFERENCES publikacija(ID_P) ON DELETE CASCADE,
        CONSTRAINT CHK_TIP_CITATA CHECK (TIP_CITATA IN ('INDIREKTAN','DIREKTAN'))
    );

-------------------------------------------------------------------------------------------------------------------
--Autorstvo

CREATE TABLE autorstvo(
    ID_U NUMBER(10) NOT NULL,
    ID_P NUMBER(10) NOT NULL,
    REDNI_BROJ_AUTORA NUMBER(10) NOT NULL,
    TIP_DOPRINOSA VARCHAR2(100) NOT NULL,
    ULOGA_U_PUBLIKACIJI VARCHAR2(100) NOT NULL,

    CONSTRAINT PK_AUTORSTVO PRIMARY KEY (ID_U, ID_P),
    CONSTRAINT FK_AUTORSTVO_ID_U FOREIGN KEY (ID_U) REFERENCES uloga(ID_U) ON DELETE CASCADE,
    CONSTRAINT FK_AUTORSTVO_ID_P FOREIGN KEY (ID_P) REFERENCES publikacija(ID_P) ON DELETE CASCADE
);
------------------------------------------------------------------------------------------------------------------
--Runda recenzije

CREATE TABLE runda_recenzije(
    ID_P NUMBER(10) NOT NULL,
    ID_UREDNIKA NUMBER(10) NOT NULL,
    --ID_RECENZENTA NUMBER(10) NOT NULL,
    BROJ_RUNDE NUMBER(10) NOT NULL,
    DATUM_ODLUKE DATE NOT NULL,
    KONACNA_ODLUKA VARCHAR2(20) DEFAULT 'POTREBNA_REVIZIJA' NOT NULL,

    CONSTRAINT PK_RR PRIMARY KEY (ID_P,BROJ_RUNDE),
    --Angazovanje urednika i runde recenzije (1:N)
    CONSTRAINT FK_RR_ID_UREDNIKA FOREIGN KEY (ID_UREDNIKA) REFERENCES urednik(ID_U) ON DELETE CASCADE,
    --CONSTRAINT FK_RR_ID_RECENZENTA FOREIGN KEY (ID_RECENZENTA) REFERENCES recenzent(ID_U) ON DELETE CASCADE,
    CONSTRAINT FK_RR_ID_P FOREIGN KEY (ID_P) REFERENCES publikacija(ID_P) ON DELETE CASCADE,
    CONSTRAINT CHK_KONACNA_ODLUKA CHECK (KONACNA_ODLUKA IN ('POTREBNA_REVIZIJA','PRIHVACENA','ODBIJENA'))
);

    --Angazovanje recenzenti
    CREATE TABLE angazovanje_recenzent(
        ID_P NUMBER(10) NOT NULL,
        ID_RECENZENTA NUMBER(10) NOT NULL,
        BROJ_RUNDE NUMBER(10) NOT NULL,
        PREPORUKA VARCHAR2(10) DEFAULT 'NE' NOT NULL,

        CONSTRAINT CHK_PREPORUKA CHECK (PREPORUKA IN ('DA','NE')),
        CONSTRAINT PK_ANG_REC PRIMARY KEY (ID_P, ID_RECENZENTA, BROJ_RUNDE),
        CONSTRAINT FK_ANG_REC_ID_RUN_REC FOREIGN KEY (ID_P,BROJ_RUNDE) REFERENCES runda_recenzije(ID_P,BROJ_RUNDE) ON DELETE CASCADE,
        CONSTRAINT FK_ANG_REC_ID_REC FOREIGN KEY (ID_RECENZENTA) REFERENCES recenzent(ID_U) ON DELETE CASCADE
    );

        --Ocena recenzenta atribut
        CREATE TABLE ocena_recenzenta(
            ID_O NUMBER(10) PRIMARY KEY,
            ID_P NUMBER(10) NOT NULL,
            ID_RECENZENTA NUMBER(10) NOT NULL,
            BROJ_RUNDE NUMBER(10) NOT NULL,
            OCENA NUMBER(1) NOT NULL,

            CONSTRAINT CHK_OCENA CHECK (OCENA BETWEEN 1 AND 5),
            --CONSTRAINT PK_OCENA PRIMARY KEY (ID_P, ID_RECENZENTA,BROJ_RUNDE,OCENA),
            CONSTRAINT FK_OCENA_ID_ANG_REC FOREIGN KEY (ID_P, ID_RECENZENTA, BROJ_RUNDE) REFERENCES angazovanje_recenzent(ID_P, ID_RECENZENTA, BROJ_RUNDE) ON DELETE CASCADE
            --CONSTRAINT FK_OCENA_ID_REC FOREIGN KEY (ID_RECENZENTA) REFERENCES recenzent(ID_U) ON DELETE CASCADE
        );
-------------------------------------------------------------------------------------------------------------------
-- Ureduje
CREATE TABLE uredjuje(
    ID_IR NUMBER(10) NOT NULL,
    ID_UREDNIKA NUMBER(10) NOT NULL,

    CONSTRAINT PK_UREDI PRIMARY KEY (ID_IR, ID_UREDNIKA),
    CONSTRAINT FK_UREDI_ID_IR FOREIGN KEY (ID_IR) REFERENCES istrazivacki_rezultat(ID_IR) ON DELETE CASCADE,
    CONSTRAINT FK_UREDI_ID_UREDNIKA FOREIGN KEY (ID_UREDNIKA) REFERENCES urednik(ID_U) ON DELETE CASCADE
);
-------------------------------------------------------------------------------------------------------------------
--Unos test podataka
DECLARE
    new_ID_IR istrazivacki_rezultat.ID_IR%TYPE;
    new_ID_P publikacija.ID_P%TYPE;
    new_ID_U uloga.ID_U%TYPE;
    new_ID_I istrazivac.ID_I%TYPE;
    new_ID_NII ni_institucija.ID_NII%TYPE;

BEGIN
    -- Kreiranje entiteta roditelja; ID se sada eksplicitno uzima iz sekvence
    INSERT INTO istrazivacki_rezultat(ID_IR, NASLOV,APSTRAKT, DATUM_KREIRANJA, DATUM_OBJAVLJIVANJA, STATUS_IR, VIDLJIVOST)
    VALUES (SEQ_ISTRAZIVACKI_REZULTAT.NEXTVAL, 'Uticaj udica na ajkule','Prvi istrazivacki rezultat u bazi',TO_DATE('2023-01-01', 'YYYY-MM-DD'),TO_DATE('2026-02-14', 'YYYY-MM-DD'),'POSLAT_NA_RECENZIJU','1')
    RETURNING ID_IR INTO new_ID_IR;

    -- Kreiranje entiteta koji koristi sacuvani ID kao FK
    INSERT INTO ostali_dokumenti(ID_IR, OPCIJE)
    VALUES (new_ID_IR, 'OBRAZOVNI_MATERIJAL');

    INSERT INTO kljucne_reci (ID_IR,KLJUCNA_REC)
    VALUES (new_ID_IR, 'Ajkula');
    INSERT INTO kljucne_reci (ID_IR,KLJUCNA_REC)
    VALUES (new_ID_IR, 'Udica');
    INSERT INTO kljucne_reci (ID_IR,KLJUCNA_REC)
    VALUES (new_ID_IR, 'Ekologija');

    INSERT INTO  verzija(ID_IR,BROJ_VERZIJE,DATUM_POSTAVLJANJA,OPIS_IZMENA,ODGOVORNA_OSOBA)
    VALUES (new_ID_IR, 1, TO_DATE('2024-02-14', 'YYYY-MM-DD'), 'Dodatna pojasnjenja neprecizno definisanih pojmova', 'Marko Nikolic');
    INSERT INTO  pripadajuci_fajlovi(ID_IR,BROJ_VERZIJE, NAZIV_FAJLA)
    VALUES (new_ID_IR, 1, 'Fajl br. 1');
    INSERT INTO  pripadajuci_fajlovi(ID_IR,BROJ_VERZIJE, NAZIV_FAJLA)
    VALUES (new_ID_IR, 1, 'Fajl br. 2');

    INSERT INTO  verzija(ID_IR,BROJ_VERZIJE,DATUM_POSTAVLJANJA,OPIS_IZMENA,ODGOVORNA_OSOBA)
    VALUES (new_ID_IR, 2, TO_DATE('2025-02-11', 'YYYY-MM-DD'), 'Ispravke gresaka u kucanju', 'Pera Peric');
    INSERT INTO  pripadajuci_fajlovi(ID_IR,BROJ_VERZIJE, NAZIV_FAJLA)
    VALUES (new_ID_IR, 2, 'Fajl br. 1');
    INSERT INTO  pripadajuci_fajlovi(ID_IR,BROJ_VERZIJE, NAZIV_FAJLA)
    VALUES (new_ID_IR, 2, 'Fajl br. 2');
    --------------------------------------------------------------------------------------------------------------------------------------------------
    INSERT INTO istrazivacki_rezultat(ID_IR, NASLOV,APSTRAKT, DATUM_KREIRANJA, DATUM_OBJAVLJIVANJA, STATUS_IR, VIDLJIVOST)
    VALUES (SEQ_ISTRAZIVACKI_REZULTAT.NEXTVAL, 'Efekat staklene baste','Drugi istrazivacki rezultat u bazi',TO_DATE('2026-01-01', 'YYYY-MM-DD'),TO_DATE('2026-08-14', 'YYYY-MM-DD'),'OBJAVLJEN','1')
    RETURNING ID_IR INTO new_ID_IR;

    INSERT INTO istrazivac(ID_I, IME, DATUM_RODJENJA,DRZAVA,PREZIME, NAUCNA_OBLAST,NAUCNO_ZVANJE,STATUS_NAUCNIKA)
    VALUES(SEQ_ISTRAZIVAC.NEXTVAL, 'Andrej', TO_DATE('1989-12-23', 'YYYY-MM-DD'), 'Bugarska', 'Bugalkov', 'Ekologija','Magistar biologije', 'AKTIVAN')
    RETURNING ID_I into new_ID_I;

    INSERT INTO mail(ID_I, MAIL)
    VALUES(new_ID_I, 'AndrejBugalkov@gmail.com');
    INSERT INTO mail(ID_I, MAIL)
    VALUES(new_ID_I, 'AB89@gmail.com');

    INSERT INTO telefon(ID_I, TELEFON)
    VALUES(new_ID_I, '+381632327744');
    INSERT INTO telefon(ID_I, TELEFON)
    VALUES(new_ID_I, '+38160552424');

    INSERT INTO dataset(ID_IR, FORMAT,VELICINA, BROJ_ZAPISA, OPIS_STRUKTURE, PERIOD_OBUHVATA_PODATAKA, LICENCA_KORISCENJA, OGRANICENJA_PRISTUPA)
    VALUES (new_ID_IR, 'JSON', '1024', 20, 'standardna struktura', ' od 10-10-2010 do 11-11-2010', 'Markova licenca', 'read-only');

    INSERT INTO kljucne_reci (ID_IR,KLJUCNA_REC)
    VALUES (new_ID_IR, 'Staklena basta');
    INSERT INTO kljucne_reci (ID_IR,KLJUCNA_REC)
    VALUES (new_ID_IR, 'Globalno zagrevanje');
    INSERT INTO kljucne_reci (ID_IR,KLJUCNA_REC)
    VALUES (new_ID_IR, 'Ekologija');

    /*INSERT INTO publikacija (ID_P, ID_IR)
    VALUES (SEQ_PUBLIKACIJA.NEXTVAL, new_ID_IR)
    RETURNING ID_P INTO new_ID_P;*/

    INSERT INTO uloga(ID_U, ID_I)
    VALUES(SEQ_ULOGA.NEXTVAL, new_ID_I) 
    RETURNING ID_U INTO new_ID_U;

    INSERT INTO autor(ID_U, ORCID)
    VALUES(new_ID_U, '1234-0002-1825-009X');

    --INSERT INTO autorstvo(ID_U, ID_P, REDNI_BROJ_AUTORA,TIP_DOPRINOSA, ULOGA_U_PUBLIKACIJI)
    --VALUES(new_ID_U,new_ID_P, 1,'Istrazivao uticaj emisija stetnih gasova iz automobila na efekat staklene baste', '23-50 strana');
    -----------------------------------------------------------------------------------------------------------------------------------------------------
    Insert into istrazivacki_rezultat(ID_IR, NASLOV,APSTRAKT, DATUM_KREIRANJA, DATUM_OBJAVLJIVANJA, STATUS_IR, VIDLJIVOST)
    values (SEQ_ISTRAZIVACKI_REZULTAT.NEXTVAL, 'Negativni efekti duvanskig dima','Treci istrazivacki rezultat u bazi',TO_DATE('2016-02-01', 'YYYY-MM-DD'),TO_DATE('2021-07-14', 'YYYY-MM-DD'),'ARHIVIRAN','0')
    RETURNING ID_IR INTO new_ID_IR;

    INSERT INTO softverski_artifakt(ID_IR, PROGRAMSKI_JEZIK,REPO_LINK, NACIN_LICENCIRANJA, DOKUMENTACIJA)
    VALUES (new_ID_IR, 'c++', 'www.github.com', 'SaaS', 'dokument.txt');

    INSERT INTO podrzane_platforme(ID_IR, PLATFORMA)
    VALUES(new_ID_IR, 'WINDOWS');
    INSERT INTO podrzane_platforme(ID_IR, PLATFORMA)
    VALUES (new_ID_IR, 'MACOS');
    INSERT INTO podrzane_platforme(ID_IR, PLATFORMA)
    VALUES(new_ID_IR, 'LINUX');
    -----------------------------------------------------------------------------------------------------------------------------------------------------
    INSERT INTO istrazivac(ID_I, IME, DATUM_RODJENJA,DRZAVA,PREZIME, NAUCNA_OBLAST,NAUCNO_ZVANJE,STATUS_NAUCNIKA)
    VALUES(SEQ_ISTRAZIVAC.NEXTVAL, 'Petar', TO_DATE('1967-02-23', 'YYYY-MM-DD'), 'Srbija', 'Petrovic', 'Matematika','Doktor matematickih nauka', 'AKTIVAN')
    RETURNING ID_I into new_ID_I;

    INSERT INTO mail(ID_I, MAIL)
    VALUES(new_ID_I, 'PetarPetrovic@gmail.com');
    INSERT INTO mail(ID_I, MAIL)
    VALUES(new_ID_I, 'PeraZdera67@gmail.com');

    INSERT INTO telefon(ID_I, TELEFON)
    VALUES(new_ID_I, '+381632224444');
    INSERT INTO telefon(ID_I, TELEFON)
    VALUES(new_ID_I, '+38163555444');


    INSERT INTO uloga(ID_U, ID_I)
    VALUES(SEQ_ULOGA.NEXTVAL, new_ID_I)
    RETURNING ID_U INTO new_ID_U;

    INSERT INTO recenzent(ID_U)
    VALUES(new_ID_U);

    INSERT INTO oblasti_ekspertize(ID_U,OBLAST_EKSPERTIZE)
    VALUES(new_ID_U, 'Matematika');
    INSERT INTO oblasti_ekspertize(ID_U,OBLAST_EKSPERTIZE)
    VALUES(new_ID_U, 'Racunarske nauke');
    INSERT INTO oblasti_ekspertize(ID_U,OBLAST_EKSPERTIZE)
    VALUES(new_ID_U, 'Fizika');



    INSERT INTO ni_institucija(ID_NII, NAZIV, ADRESA)
    VALUES(SEQ_NI_INSTITUCIJA.NEXTVAL, 'Matematicki institut', 'Narodnih heroja BB')
    RETURNING ID_NII INTO new_ID_NII;

    INSERT INTO naucna_oblast(ID_NII, NAUCNA_OBLAST)
    VALUES(new_ID_NII, 'Matematika');

    INSERT INTO naucna_oblast(ID_NII, NAUCNA_OBLAST)
    VALUES(new_ID_NII, 'Fizika');

    INSERT INTO mail_institucija(ID_NII, MAIL)
    VALUES(new_ID_NII, 'MatematickiInstitut@gmail.com');
    INSERT INTO mail_institucija(ID_NII, MAIL)
    VALUES(new_ID_NII, 'DepartmanZaMatematiku@gmail.com');

    INSERT INTO telefon_institucija(ID_NII, TELEFON)
    VALUES(new_ID_NII, '+38161234678');
    INSERT INTO telefon_institucija(ID_NII, TELEFON)
    VALUES(new_ID_NII, '+38160555432');

    INSERT INTO angazovanje(ID_I, ID_NII, DATUM_ANGAZOVANJA, DATUM_ZAVRSETKA, ORGANIZACIONA_JEDINICA, NAZIV_POZICIJE, TIP_ANGAZOVANJA)
    VALUES(new_ID_I,new_ID_NII, TO_DATE('2014-02-23', 'YYYY-MM-DD'),TO_DATE('2028-02-23', 'YYYY-MM-DD'), 'Matematicki fakultet', 'Profesor', 'PRIVREMEN');



    COMMIT;
END;



